root = "."
tmp_dir = "tmp"

[build]
cmd = "./build-wasm.sh"
bin = ""
full_bin = ""
include_ext = ["go"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air_errors.log"
no_run = true

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = false 